# Generated by Django 5.2.7 on 2025-10-03 03:25

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cache do Dashboard',
                'verbose_name_plural': 'Caches do Dashboard',
            },
        ),
        migrations.CreateModel(
            name='DengueStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatística de Dengue',
                'verbose_name_plural': 'Estatísticas de Dengue',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_uf', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('total_casos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('total_casos', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='CasoDengue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_notificacao', models.DateField()),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('I', 'Ignorado')], max_length=1)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('febre', models.BooleanField(default=False)),
                ('mialgia', models.BooleanField(default=False)),
                ('cefaleia', models.BooleanField(default=False)),
                ('exantema', models.BooleanField(default=False)),
                ('vomito', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('classificacao_final', models.IntegerField(blank=True, choices=[(10, 'Confirmado'), (8, 'Descartado'), (11, 'Inconclusivo'), (12, 'Óbito por dengue')], null=True)),
                ('evolucao', models.IntegerField(blank=True, choices=[(1, 'Cura'), (2, 'Óbito por dengue'), (3, 'Óbito por outras causas'), (4, 'Óbito em investigação'), (9, 'Ignorado')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.municipio')),
            ],
            options={
                'verbose_name': 'Caso de Dengue',
                'verbose_name_plural': 'Casos de Dengue',
                'ordering': ['-data_notificacao'],
            },
        ),
    ]
